version: '3'

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-cache-data:/data
    ports:
      - "6379:6379"

  artemis:
    image: artemis-ubuntu
    container_name: artemis
    ports:
      - "61616:61616"
      - "8161:8161"

  consul:
    image: consul
    container_name: consul
    hostname: localhost
    volumes:
      - consul-data:/consul/data
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=localhost -bootstrap-expect=1 -client=0.0.0.0"

  postgres:
    image: postgres
    volumes:
      - operations-data:/var/lib/postgresql/data
    container_name: db
    ports:
      - '2345:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=OperationsDB'
volumes:
  operations-data:
  redis-cache-data:
  consul-data:
