server:
  port: ${random.int(8200,8300)}

spring:
  application:
    name: divisionService

  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
