spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: springMvcCalculator

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false

service:
  name:
    addition: additionService
    subtraction: subtractionService
    multiplication: multiplicationService
    division: divisionService


management:
  endpoints:
    web:
      exposure:
        include: '*'